-- Configure the ansiblels language server
-- I'm beginning to think this is unnecessary, but don't know how to fix the linting errors.  If you look at LSP
-- logs in ~/.local/state/nvim/lsp.log without any of this, you'll see the lint output appears to be stdout human
-- readable, which is obviously not consumable by LSP client.  All of this is an attempt to force a JSON output
-- format, but attempts to do so seem to break the LSP server.  See some code implementation here:
-- https://github.com/ansible/vscode-ansible/blob/2a9931776c0bd4db87627ad8b1af6648d6a223cb/packages/ansible-language-server/src/services/ansibleLint.ts#L56
--
-- Also, WTF about all of this is unique to having issues linting Ansible role project, but not playbook projects or
-- seemingly anything else that is registered as an "ansible" document type.
-- require("lspconfig").ansiblels.setup({
--   -- Add any other configurations for ansiblels here
--   -- Example: Add custom arguments to ansible-lint
--   settings = {
--     ansible = {
--       ansibleLint = {
--         arguments = {
--           "--format",
--           "codeclimate", -- Force CodeClimate/JSON output format
--         },
--       },
--       -- validation = {
--       --   -- enabled = true,
--       --   lint = {
--       --     -- enabled = true,
--       --     arguments = {
--       --       "--format",
--       --       "codeclimate",
--       --     },
--       --     -- path = "ansible-lint",
--       --   },
--       -- },
--     },
--   },
-- })
