-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
--
vim.cmd("autocmd BufRead,BufNewFile *.yml set filetype=yaml.ansible")
-- vim.cmd("autocmd CursorMoved * :lua echo_diagnostic()")
--
-- polish = function()
--   require("notify").setup({
--     background_colour = "#C0C0C0",
--   })
-- end
